export const popularShoesList = [
  // Nike
  { name: 'Nike Alphafly 3', category: 'racing', brand: 'Nike' },
  { name: 'Nike Alphafly 4', category: 'racing', brand: 'Nike' },
  { name: 'Nike Vaporfly 3', category: 'racing', brand: 'Nike' },
  { name: 'Nike Vaporfly 4', category: 'racing', brand: 'Nike' },
  { name: 'Nike ZoomX Streakfly', category: 'racing', brand: 'Nike' },
  { name: 'Nike Air Zoom Pegasus 40', category: 'daily', brand: 'Nike' },
  { name: 'Nike Air Zoom Pegasus 41', category: 'daily', brand: 'Nike' },
  { name: 'Nike Air Zoom Pegasus 42', category: 'daily', brand: 'Nike' },
  { name: 'Nike Vomero 17', category: 'cushion', brand: 'Nike' },
  { name: 'Nike Vomero 18', category: 'cushion', brand: 'Nike' },
  { name: 'Nike Invincible 3', category: 'cushion', brand: 'Nike' },
  { name: 'Nike Invincible 4', category: 'cushion', brand: 'Nike' },
  { name: 'Nike Infinity Run 4', category: 'daily', brand: 'Nike' },
  { name: 'Nike Structure 25', category: 'daily', brand: 'Nike' },
  { name: 'Nike Wildhorse 8', category: 'trail', brand: 'Nike' },
  { name: 'Nike Terra Kiger 9', category: 'trail', brand: 'Nike' },
  { name: 'Nike Zegama 2', category: 'trail', brand: 'Nike' },
  { name: 'Nike Pegasus Trail 5', category: 'trail', brand: 'Nike' },
  { name: 'Nike Ultrafly Trail', category: 'trail', brand: 'Nike' },
  // Adidas
  { name: 'Adidas Adizero Adios Pro 3', category: 'racing', brand: 'Adidas' },
  { name: 'Adidas Adizero Adios Pro 4', category: 'racing', brand: 'Adidas' },
  { name: 'Adidas Adizero Prime X 2 Strung', category: 'racing', brand: 'Adidas' },
  { name: 'Adidas Adizero Takumi Sen 10', category: 'racing', brand: 'Adidas' },
  { name: 'Adidas Adizero Evo SL', category: 'daily', brand: 'Adidas' },
  { name: 'Adidas Adizero Boston 12', category: 'daily', brand: 'Adidas' },
  { name: 'Adidas Adizero Boston 13', category: 'daily', brand: 'Adidas' },
  { name: 'Adidas Adizero Adios 8', category: 'daily', brand: 'Adidas' },
  { name: 'Adidas Supernova Rise', category: 'daily', brand: 'Adidas' },
  { name: 'Adidas Supernova Solution', category: 'daily', brand: 'Adidas' },
  { name: 'Adidas Ultraboost Light', category: 'cushion', brand: 'Adidas' },
  { name: 'Adidas Ultraboost 5', category: 'cushion', brand: 'Adidas' },
  { name: 'Adidas Terrex Speed Ultra', category: 'trail', brand: 'Adidas' },
  { name: 'Adidas Terrex Agravic Speed Ultra', category: 'trail', brand: 'Adidas' },
  // Asics
  { name: 'Asics Metaspeed Sky Paris', category: 'racing', brand: 'Asics' },
  { name: 'Asics Metaspeed Edge Paris', category: 'racing', brand: 'Asics' },
  { name: 'Asics Magic Speed 4', category: 'racing', brand: 'Asics' },
  { name: 'Asics Superblast 2', category: 'cushion', brand: 'Asics' },
  { name: 'Asics Novablast 4', category: 'daily', brand: 'Asics' },
  { name: 'Asics Novablast 5', category: 'daily', brand: 'Asics' },
  { name: 'Asics Gel-Kayano 31', category: 'cushion', brand: 'Asics' },
  { name: 'Asics Gel-Kayano 32', category: 'cushion', brand: 'Asics' },
  { name: 'Asics Gel-Nimbus 26', category: 'cushion', brand: 'Asics' },
  { name: 'Asics Gel-Nimbus 27', category: 'cushion', brand: 'Asics' },
  { name: 'Asics Gel-Cumulus 26', category: 'daily', brand: 'Asics' },
  { name: 'Asics GT-2000 12', category: 'daily', brand: 'Asics' },
  { name: 'Asics Glideride Max', category: 'cushion', brand: 'Asics' },
  { name: 'Asics Fuji Speed 2', category: 'trail', brand: 'Asics' },
  { name: 'Asics Gel-Trabuco 12', category: 'trail', brand: 'Asics' },
  // Hoka
  { name: 'Hoka Cielo X1', category: 'racing', brand: 'Hoka' },
  { name: 'Hoka Rocket X 2', category: 'racing', brand: 'Hoka' },
  { name: 'Hoka Mach 6', category: 'daily', brand: 'Hoka' },
  { name: 'Hoka Mach 7', category: 'daily', brand: 'Hoka' },
  { name: 'Hoka Clifton 9', category: 'daily', brand: 'Hoka' },
  { name: 'Hoka Clifton 10', category: 'daily', brand: 'Hoka' },
  { name: 'Hoka Bondi 8', category: 'cushion', brand: 'Hoka' },
  { name: 'Hoka Bondi 9', category: 'cushion', brand: 'Hoka' },
  { name: 'Hoka Skyward X', category: 'cushion', brand: 'Hoka' },
  { name: 'Hoka Rincon 4', category: 'daily', brand: 'Hoka' },
  { name: 'Hoka Speedgoat 6', category: 'trail', brand: 'Hoka' },
  { name: 'Hoka Mafate Speed 4', category: 'trail', brand: 'Hoka' },
  { name: 'Hoka Tecton X 3', category: 'trail', brand: 'Hoka' },
  { name: 'Hoka Challenger 7', category: 'trail', brand: 'Hoka' },
  // New Balance
  { name: 'New Balance FuelCell SuperComp Elite v4', category: 'racing', brand: 'New Balance' },
  { name: 'New Balance FuelCell SuperComp Elite v5', category: 'racing', brand: 'New Balance' },
  { name: 'New Balance FuelCell SuperComp Trainer v2', category: 'cushion', brand: 'New Balance' },
  { name: 'New Balance FuelCell Rebel v4', category: 'daily', brand: 'New Balance' },
  { name: 'New Balance FuelCell Rebel v5', category: 'daily', brand: 'New Balance' },
  { name: 'New Balance Fresh Foam X 1080 v13', category: 'cushion', brand: 'New Balance' },
  { name: 'New Balance Fresh Foam X 1080 v14', category: 'cushion', brand: 'New Balance' },
  { name: 'New Balance Fresh Foam X 880 v14', category: 'daily', brand: 'New Balance' },
  { name: 'New Balance Fresh Foam X More v4', category: 'cushion', brand: 'New Balance' },
  { name: 'New Balance Fresh Foam X More v5', category: 'cushion', brand: 'New Balance' },
  { name: 'New Balance Fresh Foam X Hierro v8', category: 'trail', brand: 'New Balance' },
  { name: 'New Balance Fresh Foam X Vongo v6', category: 'cushion', brand: 'New Balance' },
  // Brooks
  { name: 'Brooks Hyperion Elite v4', category: 'racing', brand: 'Brooks' },
  { name: 'Brooks Hyperion Max 2', category: 'daily', brand: 'Brooks' },
  { name: 'Brooks Hyperion 2', category: 'daily', brand: 'Brooks' },
  { name: 'Brooks Ghost 16', category: 'daily', brand: 'Brooks' },
  { name: 'Brooks Ghost 17', category: 'daily', brand: 'Brooks' },
  { name: 'Brooks Ghost Max 2', category: 'cushion', brand: 'Brooks' },
  { name: 'Brooks Glycerin 21', category: 'cushion', brand: 'Brooks' },
  { name: 'Brooks Glycerin 22', category: 'cushion', brand: 'Brooks' },
  { name: 'Brooks Cascadia 18', category: 'trail', brand: 'Brooks' },
  { name: 'Brooks Catamount 3', category: 'trail', brand: 'Brooks' },
  // Saucony
  { name: 'Saucony Endorphin Elite', category: 'racing', brand: 'Saucony' },
  { name: 'Saucony Endorphin Pro 4', category: 'racing', brand: 'Saucony' },
  { name: 'Saucony Endorphin Pro 5', category: 'racing', brand: 'Saucony' },
  { name: 'Saucony Endorphin Speed 4', category: 'daily', brand: 'Saucony' },
  { name: 'Saucony Endorphin Speed 5', category: 'daily', brand: 'Saucony' },
  { name: 'Saucony Kinvara 15', category: 'daily', brand: 'Saucony' },
  { name: 'Saucony Ride 17', category: 'daily', brand: 'Saucony' },
  { name: 'Saucony Ride 18', category: 'daily', brand: 'Saucony' },
  { name: 'Saucony Triumph 22', category: 'cushion', brand: 'Saucony' },
  { name: 'Saucony Triumph 23', category: 'cushion', brand: 'Saucony' },
  { name: 'Saucony Hurricane 24', category: 'cushion', brand: 'Saucony' },
  { name: 'Saucony Peregrine 14', category: 'trail', brand: 'Saucony' },
  { name: 'Saucony Xodus Ultra 3', category: 'trail', brand: 'Saucony' },
  // Mizuno
  { name: 'Mizuno Wave Rebellion Pro 2', category: 'racing', brand: 'Mizuno' },
  { name: 'Mizuno Wave Rebellion Flash 2', category: 'racing', brand: 'Mizuno' },
  { name: 'Mizuno Wave Rider 28', category: 'daily', brand: 'Mizuno' },
  { name: 'Mizuno Wave Sky 8', category: 'cushion', brand: 'Mizuno' },
  { name: 'Mizuno Wave Inspire 20', category: 'daily', brand: 'Mizuno' },
  { name: 'Mizuno Wave Mujin 10', category: 'trail', brand: 'Mizuno' },
  { name: 'Mizuno Wave Daichi 8', category: 'trail', brand: 'Mizuno' },
  // Puma
  { name: 'Puma Deviate Nitro Elite 3', category: 'racing', brand: 'Puma' },
  { name: 'Puma Deviate Nitro 3', category: 'daily', brand: 'Puma' },
  { name: 'Puma Fast-R Nitro Elite 2', category: 'racing', brand: 'Puma' },
  { name: 'Puma Velocity Nitro 3', category: 'daily', brand: 'Puma' },
  { name: 'Puma Magnify Nitro 2', category: 'cushion', brand: 'Puma' },
  { name: 'Puma ForeverRun Nitro', category: 'daily', brand: 'Puma' },
  { name: 'Puma Voyage Nitro 3', category: 'trail', brand: 'Puma' },
  // Salomon
  { name: 'Salomon S/Lab Phantasm 2', category: 'racing', brand: 'Salomon' },
  { name: 'Salomon Aero Glide 2', category: 'cushion', brand: 'Salomon' },
  { name: 'Salomon Aero Volt', category: 'daily', brand: 'Salomon' },
  { name: 'Salomon Sense Ride 5', category: 'trail', brand: 'Salomon' },
  { name: 'Salomon Speedcross 6', category: 'trail', brand: 'Salomon' },
  { name: 'Salomon Ultra Glide 2', category: 'trail', brand: 'Salomon' },
  { name: 'Salomon Genesis', category: 'trail', brand: 'Salomon' },
  // On Running
  { name: 'On Cloudboom Echo 3', category: 'racing', brand: 'On' },
  { name: 'On Cloudsurfer Trail', category: 'trail', brand: 'On' },
  { name: 'On Cloudsurfer Next', category: 'daily', brand: 'On' },
  { name: 'On Cloudrunner 2', category: 'daily', brand: 'On' },
  { name: 'On Cloudmonster 2', category: 'cushion', brand: 'On' },
  { name: 'On Cloudeclipse', category: 'cushion', brand: 'On' },
  { name: 'On Cloudeclipse 2', category: 'cushion', brand: 'On' },
  { name: 'On Cloudflow 4', category: 'daily', brand: 'On' },
  { name: 'On Cloudultra 2', category: 'trail', brand: 'On' },
  // Altra
  { name: 'Altra Vanish Carbon 2', category: 'racing', brand: 'Altra' },
  { name: 'Altra Torin 7', category: 'daily', brand: 'Altra' },
  { name: 'Altra Escalante 4', category: 'daily', brand: 'Altra' },
  { name: 'Altra Paradigm 7', category: 'cushion', brand: 'Altra' },
  { name: 'Altra Olympus 6', category: 'cushion', brand: 'Altra' },
  { name: 'Altra Lone Peak 8', category: 'trail', brand: 'Altra' },
  { name: 'Altra Timp 5', category: 'trail', brand: 'Altra' }
]
